# docker-compose.yml

version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # envでrootと設定しているので、コメントアウト
      # MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
    command: --default-authentication-plugin=mysql_native_password
    container_name: mouretsu_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: rails server -b 0.0.0.0
    image: mouretsu_backend_image
    container_name: mouretsu_backend
    volumes:
      - ./backend:/mouretsu
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    image: mouretsu_frontend_image
    container_name: mouretsu_frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: "yarn dev"
    ports:
      - "8000:3000"

  # commons_ui:
  #   build:
  #     context: ./commons-ui/
  #     dockerfile: Dockerfile.dev
  #   image: yakushiru_commons_ui_image
  #   container_name: yakushiru_commons_ui
  #   volumes:
  #     - ./commons-ui:/usr/src/app
  #   command: "yarn start"
  #   ports:
  #     - "8080:3000"
  #   tty: true

volumes:
  db-data: